#jekyll serve --config _config.local.yml
title: 陶瓷片
url: http://0.0.0.0:4000

markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title

lsi: false
paginate: 20

gems: [jekyll-paginate]

exclude:
- CNAME
