title: 陶瓷片
url: http://taocp.github.io

markdown: kramdown
highlighter: rouge
#permalink: /:year/:month/:day/:title
permalink: /:title

lsi: false
paginate: 20

gems: [jekyll-paginate]

exclude:
- CNAME
