#jekyll serve --config _config.local.yml
title: 陶瓷片
url: http://0.0.0.0:4000

#markdown: rdiscount
highlighter: pygments
permalink: /:year/:month/:day/:title

lsi: false
paginate: 20

exclude:
- CNAME
